### ISSUE TITLE
runtime will panic while with the example

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/rio#6]
Rio with a very toy example works well

```rust
async fn say_hello() {
    println!("Hello")
}

fn main() {
    env_logger::init();
    debug!("Here we go, we are all good");
    //block_on(async {
    //    build_request().await.unwrap();
    //});
    block_on(say_hello());
    wait();
}
```

Exit with
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/rio_triage_await`
[2022-10-06T20:50:23Z INFO  rio_rt::runitime] Size Task: 1
Hello
➜  rio git:(macros/bugfixing) ✗ 

```

however, if the async runtime is used for real task like an https request, the runtime will go crazy, an example:

```rust
use log::{debug, info};
use rio_rt::runitime::{block_on, wait};
use surf;

async fn build_request() -> Result<(), surf::Error> {
    debug!("Running the https request");
    let mut res = surf::get("https://api.github.com/octocat").await?;
    info!("{}", res.body_string().await?);
    Ok(())
}

fn main() {
    env_logger::init();
    debug!("Here we go, we are all good");
    block_on(async {
        build_request().await.unwrap();
    });
    wait();
}

```

Exit with

```
2022-10-06T20:52:44Z INFO  rio_rt::runitime] Size Task: 1
[2022-10-06T20:52:44Z INFO  rio_rt::runitime] Size Task: 1
[2022-10-06T20:52:44Z INFO  rio_rt::runitime] Size Task: 1
[2022-10-06T20:52:44Z INFO  surf::middleware::logger::native] request completed
[2022-10-06T20:52:44Z INFO  rio_triage_await] 
                   MMM.           .MMM
                   MMMMMMMMMMMMMMMMMMM
                   MMMMMMMMMMMMMMMMMMM      _______________________________________
                  MMMMMMMMMMMMMMMMMMMMM    |                                       |
                 MMMMMMMMMMMMMMMMMMMMMMM   | Non-blocking is better than blocking. |
                MMMMMMMMMMMMMMMMMMMMMMMM   |_   ___________________________________|
                MMMM::- -:::::::- -::MMMM    |/
                 MM~:~ 00~:::::~ 00~:~MM
            .. MMMMM::.00:::+:::.00::MMMMM ..
                  .MM::::: ._. :::::MM.
                     MMMM;:::::;MMMM
              -MM        MMMMMMM
              ^  M+     MMMMMMMMM
                  MMMMMMM MM MM MM
                       MM MM MM MM
                       MM MM MM MM
                    .~~MM~MM~MM~MM~~.
                 ~~~~MM:~MM~~~MM~:MM~~~~
                ~~~~~~==~==~~~==~==~~~~~~
                 ~~~~~~==~==~==~==~~~~~~
                     :~==~==~==~==~~
    
[2022-10-06T20:52:44Z INFO  rio_rt::runitime] Size Task: 1
thread '<unnamed>' panicked at '`async fn` resumed after completion', examples/rio_triage_await/src/main.rs:15:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/core/src/panicking.rs:48:5
   3: rio_triage_await::main::{{closure}}
             at ./examples/rio_triage_await/src/main.rs:15:20
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0/library/core/src/future/mod.rs:91:19
   5: rio_rt::task::Task::poll
             at ./rt/src/task.rs:59:9
   6: rio_rt::runitime::Runtime::start::{{closure}}
             at ./rt/src/runitime.rs:38:40
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by vincenzopalazzo** [comment]
Fixed
